### ISSUE TITLE
Modelling ideas to be tried out

### ISSUE THREAD

**Issue by Zhang-Haipeng** [UBC-MDS/DSCI_522_group408#10]
Let's put all the ideas that we are about to try out here as a to-do list.
- [x] Use pandas `ewm` for weighted moving averages

**Comment by jacktan1** [comment]
- [x] Judge the accuracy of our model via a residual plot. This helps us to see if there's systematic errors.
- [ ] Maybe team composition feature should be considered? Not sure if 5 point guards is viable. 
- [ ] Maybe attack/defence features should be considered? 
- [ ] Possibly include a 'recently injured" feature? Some injuries might be minor and player might not sit out for the entire game, but they will play less.
- [ ] For logistic regression we need to figure out what kind of distribution we want.

**Comment by jnederlo** [comment]
These are great ideas to explore, but given our dataset and the time constrain of the project I don't think we'll get to do the feature analysis on team composition and 'recently injured'. The recently injured feature would be very valuable, but isn't included in our dataset. 

We engineered a feature for a players offensive contributions to the game.

As this is a continuous target (i.e. minutes played), we can't use logistic regression to model the data. The response is linear in nature, so Linear Regression and Tree Based Models are our best approach.
