### ISSUE TITLE
Team Contract

### ISSUE THREAD

**Issue by jnederlo** [UBC-MDS/DSCI_522_group408#2]
Let's discuss what we want to put in our team contract.

- [x] Create Team Contract.

**Comment by jacktan1** [comment]
Keep in good contact with team members! Use slack to communicate out of class :)

**Comment by jnederlo** [comment]
Here are my thoughts regarding a teamwork contract:

- Perhaps we can assign tasks to each team member for each milestone as opposed to assigning a role.
- Project management with Github issues for tracking.
- Should we meet outside of labs?
- Each group member should attend each lab.
- Each group member should contribute in a meaningful on each milestone.
- Each group member should be reasonably available on communication channels (slack, github, email) throughout each milestone.

**Comment by jnederlo** [comment]
Issue closed by PR #8.
