### ISSUE TITLE
Visualizations Feedback

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_group408#44]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] Great job adding figure numbers and captions! Though your captions could have been a bit more informative, overall this is a very good practice
- - [x] Figure 1:
	- - [x] This is an interesting way of showing correlations!
	- - [x] I would suggest a couple of things to improve this visualization:
	- - [x] You switch the x and y-axes so the features on the y-axis so they're more easily readable
	- - [x] I wouldn't connect the points here, it implies a relationship that doesn't exist. Consider just large) points, or a lollipop chart. This is especially a concern when there is a dramatic drop 
- - [x] Figure 2:
	- - [x] GREAT job! You limited the output to 2 decimal places, this is laudable, most people wouldn't have bothered with this, but this greatly improves readability of your table and report
- - [x] Figure 3:
	- - [x] This plot is good, but takes a fair bit of space. Consider faceting or facetwrap?
	- - [x] Optional stylistic thing: remove default grey background with theme_bw()
- - [ ] Figure 4
	- - [ ] Perfect! very readable, and immediately obvious what the message is
	- - [ ] The plot is a little too tall, consider reducing the height (but don't do it if the ylabels look too compressed)
	- - [ ] This is not something standard, but I personally would have created a dictionary with the column names as keys and a more human readable name as a value, then when plotting use the human readable names. This is probably too much work to do at this point, just something to keep in mind in the future. The feature names aren't super intuitive so you have to hunt around in the text for their interpretation. Another way is to add a table in the appendix with the column name and its corresponding human readable interpretation 
- - [x] Overall the report looks very polished and clean! Great work! Excellent work with your labels, titles, and plot choices! For every plot I was immediately able to understand what you were trying to convey.

**Comment by jnederlo** [comment]
Thanks for the great feedback @firasm . We have implemented the changes and suggestions for the plots. Changes reflected in PR #45 and PR #48.
