### ISSUE TITLE
Data Wrangling

### ISSUE THREAD

**Issue by jnederlo** [UBC-MDS/DSCI_522_group408#7]
@Zhang-Haipeng I think we need to sort each player one we query them before we get the rolling averages #5.

**Comment by jnederlo** [comment]
We can use pandas `ewm` for weighted moving averages as opposed to `rolling` with a window type. The documentation for the `exponential` window type in `rolling` is trash and doesn't work so `ewm` would be better. I think `rolling` should still be used to get averages, and we might want to supplement some of the stats with `ewm`. However, we would have to pick a decay rate, which might be difficult.

**Comment by Zhang-Haipeng** [comment]
> We can use pandas `ewm` for weighted moving averages as opposed to `rolling` with a window type. The documentation for the `exponential` window type in `rolling` is trash and doesn't work so `ewm` would be better. I think `rolling` should still be used to get averages, and we might want to supplement some of the stats with `ewm`. However, we would have to pick a decay rate, which might be difficult.

That's definitely worth trying. But maybe not for this week. I'd suggest to mark it as a `to-do`.
